using Imaar.Shared;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.UserFollows;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.UserFollows
{
    public class UserFollowsAppService : UserFollowsAppServiceBase, IUserFollowsAppService
    {
        //<suite-custom-code-autogenerated>
        public UserFollowsAppService(IUserFollowRepository userFollowRepository, UserFollowManager userFollowManager, IDistributedCache<UserFollowDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository)
            : base(userFollowRepository, userFollowManager, downloadTokenCache, userProfileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}