using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Cities
{
    public class CityManager : CityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CityManager(ICityRepository cityRepository)
            : base(cityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}