using Imaar.Shared;
using Imaar.Stories;
using Imaar.Vacancies;
using Imaar.ImaarServices;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Medias;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;
using Imaar.Medias;
using Imaar.Notifications;

namespace Imaar.Medias
{
    public class MediasAppService : MediasAppServiceBase, IMediasAppService
    {
        //<suite-custom-code-autogenerated>
        public MediasAppService(IMediaRepository mediaRepository, MediaManager mediaManager, IDistributedCache<MediaDownloadTokenCacheItem, string> downloadTokenCache)
            : base(mediaRepository, mediaManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        [AllowAnonymous]
        public async Task<MediaDto> GetFirstMediaByEntityIdAsync(Guid entityId, MediaEntityType sourceEntityType)
        {
            var media = await _mediaRepository.FirstOrDefaultAsync(m => 
                m.SourceEntityId == entityId.ToString() && 
                m.SourceEntityType == sourceEntityType);
                
            return ObjectMapper.Map<Media, MediaDto>(media);
        }
    }
}