using Imaar.Shared;
using Imaar.Stories;
using Imaar.Vacancies;
using Imaar.ImaarServices;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Medias;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Medias
{
    public class MediasAppService : MediasAppServiceBase, IMediasAppService
    {
        //<suite-custom-code-autogenerated>
        public MediasAppService(IMediaRepository mediaRepository, MediaManager mediaManager, IDistributedCache<MediaDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.ImaarServices.ImaarService, Guid> imaarServiceRepository, IRepository<Imaar.Vacancies.Vacancy, Guid> vacancyRepository, IRepository<Imaar.Stories.Story, Guid> storyRepository)
            : base(mediaRepository, mediaManager, downloadTokenCache, imaarServiceRepository, vacancyRepository, storyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}