using Imaar.UserProfiles;
using Imaar.ImaarServices;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.ServiceEvaluations
{
    public class ServiceEvaluation : ServiceEvaluationBase
    {
        //<suite-custom-code-autogenerated>
        protected ServiceEvaluation()
        {

        }

        public ServiceEvaluation(Guid id, Guid evaluatorId, Guid imaarServiceId, int rate)
            : base(id, evaluatorId, imaarServiceId, rate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}