using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.ServiceEvaluations
{
    public class ServiceEvaluationManager : ServiceEvaluationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ServiceEvaluationManager(IServiceEvaluationRepository serviceEvaluationRepository)
            : base(serviceEvaluationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}