using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Advertisements
{
    public class AdvertisementManager : AdvertisementManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AdvertisementManager(IAdvertisementRepository advertisementRepository)
            : base(advertisementRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}