using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Advertisements
{
    public class Advertisement : AdvertisementBase
    {
        //<suite-custom-code-autogenerated>
        protected Advertisement()
        {

        }

        public Advertisement(Guid id, Guid? userProfileId, string file, int order, bool isActive, string? title = null, string? subTitle = null, DateTime? fromDateTime = null, DateTime? toDateTime = null)
            : base(id, userProfileId, file, order, isActive, title, subTitle, fromDateTime, toDateTime)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}