using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.ServiceTicketTypes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.ServiceTicketTypes
{
    public class ServiceTicketTypesAppService : ServiceTicketTypesAppServiceBase, IServiceTicketTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceTicketTypesAppService(IServiceTicketTypeRepository serviceTicketTypeRepository, ServiceTicketTypeManager serviceTicketTypeManager, IDistributedCache<ServiceTicketTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(serviceTicketTypeRepository, serviceTicketTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}