using Imaar.ServiceTickets;
using Imaar.ServiceTickets;
using Imaar.ServiceTickets;
using Imaar.ServiceTickets;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.ServiceTickets
{
    public class ServiceTicketManager : ServiceTicketManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ServiceTicketManager(IServiceTicketRepository serviceTicketRepository)
            : base(serviceTicketRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}