using Imaar.ServiceTickets;
using Imaar.ServiceTicketTypes;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.ServiceTickets
{
    public class ServiceTicket : ServiceTicketBase
    {
        //<suite-custom-code-autogenerated>
        protected ServiceTicket()
        {

        }

        public ServiceTicket(Guid id, Guid serviceTicketTypeId, Guid ticketCreatorId, string description, TicketEntityType ticketEntityType, string ticketEntityId)
            : base(id, serviceTicketTypeId, ticketCreatorId, description, ticketEntityType, ticketEntityId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}