using Imaar.Shared;
using Imaar.UserProfiles;
using Imaar.ServiceTicketTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.ServiceTickets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.ServiceTickets
{
    public class ServiceTicketsAppService : ServiceTicketsAppServiceBase, IServiceTicketsAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceTicketsAppService(IServiceTicketRepository serviceTicketRepository, ServiceTicketManager serviceTicketManager, IDistributedCache<ServiceTicketDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.ServiceTicketTypes.ServiceTicketType, Guid> serviceTicketTypeRepository, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository)
            : base(serviceTicketRepository, serviceTicketManager, downloadTokenCache, serviceTicketTypeRepository, userProfileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}