using Imaar.Shared;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Advertisements;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Advertisements
{
    public class AdvertisementsAppService : AdvertisementsAppServiceBase, IAdvertisementsAppService
    {
        //<suite-custom-code-autogenerated>
        public AdvertisementsAppService(IAdvertisementRepository advertisementRepository, AdvertisementManager advertisementManager, IDistributedCache<AdvertisementDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository)
            : base(advertisementRepository, advertisementManager, downloadTokenCache, userProfileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}