using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Evalauations
{
    public class Evalauation : EvalauationBase
    {
        //<suite-custom-code-autogenerated>
        protected Evalauation()
        {

        }

        public Evalauation(Guid id, Guid evaluatord, Guid evaluatedPersonId, int speedOfCompletion, int dealing, int cleanliness, int perfection, int price)
            : base(id, evaluatord, evaluatedPersonId, speedOfCompletion, dealing, cleanliness, perfection, price)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}