using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Evalauations
{
    public class EvalauationManager : EvalauationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EvalauationManager(IEvalauationRepository evalauationRepository)
            : base(evalauationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}