using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.UserWorksExhibitions
{
    public class UserWorksExhibition : UserWorksExhibitionBase
    {
        //<suite-custom-code-autogenerated>
        protected UserWorksExhibition()
        {

        }

        public UserWorksExhibition(Guid id, Guid userProfileId, string file, int order, string? title = null)
            : base(id, userProfileId, file, order, title)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}