using Imaar.UserSavedItems;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.UserSavedItems
{
    public class UserSavedItemManager : UserSavedItemManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UserSavedItemManager(IUserSavedItemRepository userSavedItemRepository)
            : base(userSavedItemRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}