using Imaar.UserSavedItems;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.UserSavedItems
{
    public class UserSavedItem : UserSavedItemBase
    {
        //<suite-custom-code-autogenerated>
        protected UserSavedItem()
        {

        }

        public UserSavedItem(Guid id, Guid userProfileId, string sourceId, UserSavedItemType savedItemType)
            : base(id, userProfileId, sourceId, savedItemType)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}