using Imaar.Cities;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Regions
{
    public class Region : RegionBase
    {
        //<suite-custom-code-autogenerated>
        protected Region()
        {

        }

        public Region(Guid id, Guid cityId, string name, bool isActive, int? order = null)
            : base(id, cityId, name, isActive, order)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}