using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.ServiceTicketTypes
{
    public class ServiceTicketType : ServiceTicketTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected ServiceTicketType()
        {

        }

        public ServiceTicketType(Guid id, string title, bool isActive, int? order = null)
            : base(id, title, isActive, order)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}