using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.ServiceTicketTypes
{
    public class ServiceTicketTypeManager : ServiceTicketTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ServiceTicketTypeManager(IServiceTicketTypeRepository serviceTicketTypeRepository)
            : base(serviceTicketTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}