using Imaar.TicketTypes;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Tickets
{
    public class Ticket : TicketBase
    {
        //<suite-custom-code-autogenerated>
        protected Ticket()
        {

        }

        public Ticket(Guid id, Guid ticketTypeId, Guid ticketCreatorId, Guid ticketAgainstId, string description)
            : base(id, ticketTypeId, ticketCreatorId, ticketAgainstId, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}