using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Tickets
{
    public class TicketManager : TicketManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TicketManager(ITicketRepository ticketRepository)
            : base(ticketRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}