using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.TicketTypes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.TicketTypes
{
    public class TicketTypesAppService : TicketTypesAppServiceBase, ITicketTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public TicketTypesAppService(ITicketTypeRepository ticketTypeRepository, TicketTypeManager ticketTypeManager, IDistributedCache<TicketTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(ticketTypeRepository, ticketTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}