using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.ServiceTypes
{
    public class ServiceTypeManager : ServiceTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ServiceTypeManager(IServiceTypeRepository serviceTypeRepository)
            : base(serviceTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}