using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.ServiceTypes
{
    public class ServiceType : ServiceTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected ServiceType()
        {

        }

        public ServiceType(Guid id, Guid categoryId, string title, int order, bool isActive, string? icon = null)
            : base(id, categoryId, title, order, isActive, icon)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}