using Imaar.Shared;
using Imaar.Stories;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.StoryLovers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.StoryLovers
{
    public class StoryLoversAppService : StoryLoversAppServiceBase, IStoryLoversAppService
    {
        //<suite-custom-code-autogenerated>
        public StoryLoversAppService(IStoryLoverRepository storyLoverRepository, StoryLoverManager storyLoverManager, IDistributedCache<StoryLoverDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.Stories.Story, Guid> storyRepository)
            : base(storyLoverRepository, storyLoverManager, downloadTokenCache, userProfileRepository, storyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}