using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.VerificationCodes
{
    public class VerificationCodeManager : VerificationCodeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VerificationCodeManager(IVerificationCodeRepository verificationCodeRepository)
            : base(verificationCodeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}