using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.NotificationTypes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.NotificationTypes
{
    public class NotificationTypesAppService : NotificationTypesAppServiceBase, INotificationTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public NotificationTypesAppService(INotificationTypeRepository notificationTypeRepository, NotificationTypeManager notificationTypeManager, IDistributedCache<NotificationTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(notificationTypeRepository, notificationTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}