using Imaar.StoryTicketTypes;
using Imaar.UserProfiles;
using Imaar.Stories;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.StoryTickets
{
    public class StoryTicket : StoryTicketBase
    {
        //<suite-custom-code-autogenerated>
        protected StoryTicket()
        {

        }

        public StoryTicket(Guid id, Guid storyTicketTypeId, Guid ticketCreatorId, Guid storyAgainstId, string description)
            : base(id, storyTicketTypeId, ticketCreatorId, storyAgainstId, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}