using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.StoryTickets
{
    public class StoryTicketManager : StoryTicketManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StoryTicketManager(IStoryTicketRepository storyTicketRepository)
            : base(storyTicketRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}