using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.UserProfiles
{
    public class UserProfile : UserProfileBase
    {
        //<suite-custom-code-autogenerated>
        protected UserProfile()
        {

        }

        public UserProfile(Guid id, string securityNumber, string firstName, string lastName, string phoneNumber, string email, BiologicalSex? biologicalSex = null, DateOnly? dateOfBirth = null, string? latitude = null, string? longitude = null, string? profilePhoto = null)
            : base(id, securityNumber, firstName, lastName, phoneNumber, email, biologicalSex, dateOfBirth, latitude, longitude, profilePhoto)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}