using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.BuildingFacades;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.BuildingFacades
{
    public class BuildingFacadesAppService : BuildingFacadesAppServiceBase, IBuildingFacadesAppService
    {
        //<suite-custom-code-autogenerated>
        public BuildingFacadesAppService(IBuildingFacadeRepository buildingFacadeRepository, BuildingFacadeManager buildingFacadeManager, IDistributedCache<BuildingFacadeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(buildingFacadeRepository, buildingFacadeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}