using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.StoryTicketTypes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.StoryTicketTypes
{
    public class StoryTicketTypesAppService : StoryTicketTypesAppServiceBase, IStoryTicketTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public StoryTicketTypesAppService(IStoryTicketTypeRepository storyTicketTypeRepository, StoryTicketTypeManager storyTicketTypeManager, IDistributedCache<StoryTicketTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(storyTicketTypeRepository, storyTicketTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}