using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.TicketTypes
{
    public class TicketType : TicketTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected TicketType()
        {

        }

        public TicketType(Guid id, string title, int order, bool isActive)
            : base(id, title, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}