using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.TicketTypes
{
    public class TicketTypeManager : TicketTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TicketTypeManager(ITicketTypeRepository ticketTypeRepository)
            : base(ticketTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}