using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.NotificationTypes
{
    public class NotificationTypeManager : NotificationTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public NotificationTypeManager(INotificationTypeRepository notificationTypeRepository)
            : base(notificationTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}