using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.NotificationTypes
{
    public class NotificationType : NotificationTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected NotificationType()
        {

        }

        public NotificationType(Guid id, string title)
            : base(id, title)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}