using Imaar.MainAmenities;
using Imaar.SecondaryAmenities;
using Imaar.MainAmenities;
using Imaar.SecondaryAmenities;
using Imaar.MainAmenities;
using Imaar.SecondaryAmenities;
using Imaar.MainAmenities;
using Imaar.SecondaryAmenities;
using Imaar.MainAmenities;
using Imaar.SecondaryAmenities;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Buildings
{
    public class BuildingManager : BuildingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BuildingManager(IBuildingRepository buildingRepository,
        IRepository<MainAmenity, Guid> mainAmenityRepository,
        IRepository<SecondaryAmenity, Guid> secondaryAmenityRepository)
            : base(buildingRepository, mainAmenityRepository, secondaryAmenityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}