using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.MainAmenities;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.MainAmenities
{
    public class MainAmenitiesAppService : MainAmenitiesAppServiceBase, IMainAmenitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public MainAmenitiesAppService(IMainAmenityRepository mainAmenityRepository, MainAmenityManager mainAmenityManager, IDistributedCache<MainAmenityDownloadTokenCacheItem, string> downloadTokenCache)
            : base(mainAmenityRepository, mainAmenityManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}