using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Categories
{
    public class CategoryManager : CategoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CategoryManager(ICategoryRepository categoryRepository)
            : base(categoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}