using Imaar.Shared;
using Imaar.Vacancies;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.VacancyEvaluations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.VacancyEvaluations
{
    public class VacancyEvaluationsAppService : VacancyEvaluationsAppServiceBase, IVacancyEvaluationsAppService
    {
        //<suite-custom-code-autogenerated>
        public VacancyEvaluationsAppService(IVacancyEvaluationRepository vacancyEvaluationRepository, VacancyEvaluationManager vacancyEvaluationManager, IDistributedCache<VacancyEvaluationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.Vacancies.Vacancy, Guid> vacancyRepository)
            : base(vacancyEvaluationRepository, vacancyEvaluationManager, downloadTokenCache, userProfileRepository, vacancyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}