using Imaar.UserProfiles;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Stories
{
    public class StoryManager : StoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StoryManager(IStoryRepository storyRepository)
            : base(storyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}