using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Stories
{
    public class Story : StoryBase
    {
        //<suite-custom-code-autogenerated>
        protected Story()
        {

        }

        public Story(Guid id, Guid? storyPublisherId, DateTime fromTime, DateTime expiryTime, string? title = null)
            : base(id, storyPublisherId, fromTime, expiryTime, title)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}