using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.BuildingFacades
{
    public class BuildingFacadeManager : BuildingFacadeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BuildingFacadeManager(IBuildingFacadeRepository buildingFacadeRepository)
            : base(buildingFacadeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}