using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.VacancyEvaluations
{
    public class VacancyEvaluationManager : VacancyEvaluationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VacancyEvaluationManager(IVacancyEvaluationRepository vacancyEvaluationRepository)
            : base(vacancyEvaluationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}