using Imaar.UserProfiles;
using Imaar.Vacancies;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.VacancyEvaluations
{
    public class VacancyEvaluation : VacancyEvaluationBase
    {
        //<suite-custom-code-autogenerated>
        protected VacancyEvaluation()
        {

        }

        public VacancyEvaluation(Guid id, Guid userProfileId, Guid vacancyId, int rate)
            : base(id, userProfileId, vacancyId, rate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}