using Imaar.UserProfiles;
using Imaar.Buildings;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.BuildingEvaluations
{
    public class BuildingEvaluation : BuildingEvaluationBase
    {
        //<suite-custom-code-autogenerated>
        protected BuildingEvaluation()
        {

        }

        public BuildingEvaluation(Guid id, Guid evaluatorId, Guid buildingId, int rate)
            : base(id, evaluatorId, buildingId, rate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}