using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.BuildingEvaluations
{
    public class BuildingEvaluationManager : BuildingEvaluationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BuildingEvaluationManager(IBuildingEvaluationRepository buildingEvaluationRepository)
            : base(buildingEvaluationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}