using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.FurnishingLevels
{
    public class FurnishingLevelManager : FurnishingLevelManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FurnishingLevelManager(IFurnishingLevelRepository furnishingLevelRepository)
            : base(furnishingLevelRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}