using Imaar.Shared;
using Imaar.NotificationTypes;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Notifications;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Notifications
{
    public class NotificationsAppService : NotificationsAppServiceBase, INotificationsAppService
    {
        //<suite-custom-code-autogenerated>
        public NotificationsAppService(INotificationRepository notificationRepository, NotificationManager notificationManager, IDistributedCache<NotificationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.NotificationTypes.NotificationType, Guid> notificationTypeRepository)
            : base(notificationRepository, notificationManager, downloadTokenCache, userProfileRepository, notificationTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}