using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.StoryLovers
{
    public class StoryLoverManager : StoryLoverManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StoryLoverManager(IStoryLoverRepository storyLoverRepository)
            : base(storyLoverRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}