using Imaar.UserProfiles;
using Imaar.Stories;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.StoryLovers
{
    public class StoryLover : StoryLoverBase
    {
        //<suite-custom-code-autogenerated>
        protected StoryLover()
        {

        }

        public StoryLover(Guid id, Guid userProfileId, Guid storyId)
            : base(id, userProfileId, storyId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}