using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.VacancyAdditionalFeatures;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.VacancyAdditionalFeatures
{
    public class VacancyAdditionalFeaturesAppService : VacancyAdditionalFeaturesAppServiceBase, IVacancyAdditionalFeaturesAppService
    {
        //<suite-custom-code-autogenerated>
        public VacancyAdditionalFeaturesAppService(IVacancyAdditionalFeatureRepository vacancyAdditionalFeatureRepository, VacancyAdditionalFeatureManager vacancyAdditionalFeatureManager, IDistributedCache<VacancyAdditionalFeatureDownloadTokenCacheItem, string> downloadTokenCache)
            : base(vacancyAdditionalFeatureRepository, vacancyAdditionalFeatureManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}