using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Cities;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Cities
{
    public class CitiesAppService : CitiesAppServiceBase, ICitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public CitiesAppService(ICityRepository cityRepository, CityManager cityManager, IDistributedCache<CityDownloadTokenCacheItem, string> downloadTokenCache)
            : base(cityRepository, cityManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}