using Imaar.Shared;
using Imaar.Buildings;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.BuildingEvaluations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.BuildingEvaluations
{
    public class BuildingEvaluationsAppService : BuildingEvaluationsAppServiceBase, IBuildingEvaluationsAppService
    {
        //<suite-custom-code-autogenerated>
        public BuildingEvaluationsAppService(IBuildingEvaluationRepository buildingEvaluationRepository, BuildingEvaluationManager buildingEvaluationManager, IDistributedCache<BuildingEvaluationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.Buildings.Building, Guid> buildingRepository)
            : base(buildingEvaluationRepository, buildingEvaluationManager, downloadTokenCache, userProfileRepository, buildingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}