using Imaar.Shared;
using Imaar.Cities;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Regions;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Regions
{
    public class RegionsAppService : RegionsAppServiceBase, IRegionsAppService
    {
        //<suite-custom-code-autogenerated>
        public RegionsAppService(IRegionRepository regionRepository, RegionManager regionManager, IDistributedCache<RegionDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.Cities.City, Guid> cityRepository)
            : base(regionRepository, regionManager, downloadTokenCache, cityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}