using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.SecondaryAmenities;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.SecondaryAmenities
{
    public class SecondaryAmenitiesAppService : SecondaryAmenitiesAppServiceBase, ISecondaryAmenitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public SecondaryAmenitiesAppService(ISecondaryAmenityRepository secondaryAmenityRepository, SecondaryAmenityManager secondaryAmenityManager, IDistributedCache<SecondaryAmenityDownloadTokenCacheItem, string> downloadTokenCache)
            : base(secondaryAmenityRepository, secondaryAmenityManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}