using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.VacancyAdditionalFeatures
{
    public class VacancyAdditionalFeature : VacancyAdditionalFeatureBase
    {
        //<suite-custom-code-autogenerated>
        protected VacancyAdditionalFeature()
        {

        }

        public VacancyAdditionalFeature(Guid id, string name, int order, bool isActive)
            : base(id, name, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}