using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.VacancyAdditionalFeatures
{
    public class VacancyAdditionalFeatureManager : VacancyAdditionalFeatureManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VacancyAdditionalFeatureManager(IVacancyAdditionalFeatureRepository vacancyAdditionalFeatureRepository)
            : base(vacancyAdditionalFeatureRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}