using Imaar.Notifications;
using Imaar.UserProfiles;
using Imaar.NotificationTypes;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Notifications
{
    public class Notification : NotificationBase
    {
        //<suite-custom-code-autogenerated>
        protected Notification()
        {

        }

        public Notification(Guid id, Guid userProfileId, Guid notificationTypeId, string title, string message, bool isRead, SourceEntityType sourceEntityType, DateTime? readDate = null, int? priority = null, string? sourceEntityId = null, string? senderUserId = null)
            : base(id, userProfileId, notificationTypeId, title, message, isRead, sourceEntityType, readDate, priority, sourceEntityId, senderUserId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}