using Imaar.Shared;
using Imaar.UserProfiles;
using Imaar.TicketTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.Tickets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.Tickets
{
    public class TicketsAppService : TicketsAppServiceBase, ITicketsAppService
    {
        //<suite-custom-code-autogenerated>
        public TicketsAppService(ITicketRepository ticketRepository, TicketManager ticketManager, IDistributedCache<TicketDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.TicketTypes.TicketType, Guid> ticketTypeRepository, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository)
            : base(ticketRepository, ticketManager, downloadTokenCache, ticketTypeRepository, userProfileRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}