using Imaar.Shared;
using Imaar.ImaarServices;
using Imaar.UserProfiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.ServiceEvaluations;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.ServiceEvaluations
{
    public class ServiceEvaluationsAppService : ServiceEvaluationsAppServiceBase, IServiceEvaluationsAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceEvaluationsAppService(IServiceEvaluationRepository serviceEvaluationRepository, ServiceEvaluationManager serviceEvaluationManager, IDistributedCache<ServiceEvaluationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.ImaarServices.ImaarService, Guid> imaarServiceRepository)
            : base(serviceEvaluationRepository, serviceEvaluationManager, downloadTokenCache, userProfileRepository, imaarServiceRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        
        [AllowAnonymous]
        public virtual async Task<double> GetAverageEvaluationForServiceAsync(Guid serviceId)
        {
            // Get all evaluations for the specified service
            var evaluations = await _serviceEvaluationRepository.GetListAsync(e => e.ImaarServiceId == serviceId);
            
            // If there are no evaluations, return 0
            if (!evaluations.Any())
            {
                return 0;
            }
            
            // Calculate the average rating
            double averageRating = evaluations.Average(e => e.Rate);
            
            return averageRating;
        }
    }
}