using Imaar.Medias;
using Imaar.ImaarServices;
using Imaar.Vacancies;
using Imaar.Stories;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Medias
{
    public class Media : MediaBase
    {
        //<suite-custom-code-autogenerated>
        protected Media()
        {

        }

        public Media(Guid id, string file, int order, bool isActive, MediaEntityType sourceEntityType, string sourceEntityId, string? title = null)
            : base(id, file, order, isActive, sourceEntityType, sourceEntityId, title)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}