using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Medias
{
    public class MediaManager : MediaManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MediaManager(IMediaRepository mediaRepository)
            : base(mediaRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}