using Imaar.Shared;
using Imaar.Stories;
using Imaar.UserProfiles;
using Imaar.StoryTicketTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.StoryTickets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Imaar.Shared;

namespace Imaar.StoryTickets
{
    public class StoryTicketsAppService : StoryTicketsAppServiceBase, IStoryTicketsAppService
    {
        //<suite-custom-code-autogenerated>
        public StoryTicketsAppService(IStoryTicketRepository storyTicketRepository, StoryTicketManager storyTicketManager, IDistributedCache<StoryTicketDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Imaar.StoryTicketTypes.StoryTicketType, Guid> storyTicketTypeRepository, IRepository<Imaar.UserProfiles.UserProfile, Guid> userProfileRepository, IRepository<Imaar.Stories.Story, Guid> storyRepository)
            : base(storyTicketRepository, storyTicketManager, downloadTokenCache, storyTicketTypeRepository, userProfileRepository, storyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}