using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.SecondaryAmenities
{
    public class SecondaryAmenityManager : SecondaryAmenityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SecondaryAmenityManager(ISecondaryAmenityRepository secondaryAmenityRepository)
            : base(secondaryAmenityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}