using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.StoryTicketTypes
{
    public class StoryTicketTypeManager : StoryTicketTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StoryTicketTypeManager(IStoryTicketTypeRepository storyTicketTypeRepository)
            : base(storyTicketTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}