using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.StoryTicketTypes
{
    public class StoryTicketType : StoryTicketTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected StoryTicketType()
        {

        }

        public StoryTicketType(Guid id, string title, int order, bool isActive)
            : base(id, title, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}