using Imaar.Vacancies;
using Imaar.ServiceTypes;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.Vacancies
{
    public class Vacancy : VacancyBase
    {
        //<suite-custom-code-autogenerated>
        protected Vacancy()
        {

        }

        public Vacancy(Guid id, Guid serviceTypeId, Guid userProfileId, string title, string description, string location, string number, DateOnly dateOfPublish, BiologicalSex biologicalSex, int viewCounter, int orderCounter, string? latitude = null, string? longitude = null, string? expectedExperience = null, string? educationLevel = null, string? workSchedule = null, string? employmentType = null, string? languages = null, string? driveLicense = null, string? salary = null)
            : base(id, serviceTypeId, userProfileId, title, description, location, number, dateOfPublish, biologicalSex, viewCounter, orderCounter, latitude, longitude, expectedExperience, educationLevel, workSchedule, employmentType, languages, driveLicense, salary)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}