using Imaar.Vacancies;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.Vacancies
{
    public class VacancyManager : VacancyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VacancyManager(IVacancyRepository vacancyRepository)
            : base(vacancyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}