using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.UserFollows
{
    public class UserFollowManager : UserFollowManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UserFollowManager(IUserFollowRepository userFollowRepository)
            : base(userFollowRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}