using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.UserFollows
{
    public class UserFollow : UserFollowBase
    {
        //<suite-custom-code-autogenerated>
        protected UserFollow()
        {

        }

        public UserFollow(Guid id, Guid followerUserId, Guid followingUserId)
            : base(id, followerUserId, followingUserId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}