using Imaar.ServiceTypes;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;
using Imaar.Medias;

namespace Imaar.ImaarServices
{
    public class ImaarServiceWithDetails : ImaarServiceWithNavigationPropertiesBase
    {
        //<suite-custom-code-autogenerated>
        public virtual List<Media> Medias { get; set; }
        public ImaarServiceWithDetails()
        {

        }

        //Write your custom code...
    }
}