using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.ImaarServices
{
    public class ImaarServiceManager : ImaarServiceManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ImaarServiceManager(IImaarServiceRepository imaarServiceRepository)
            : base(imaarServiceRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}