using Imaar.ServiceTypes;
using Imaar.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Imaar.ImaarServices
{
    public class ImaarService : ImaarServiceBase
    {
        //<suite-custom-code-autogenerated>
        protected ImaarService()
        {

        }

        public ImaarService(Guid id, Guid serviceTypeId, Guid userProfileId, string title, string description, string serviceLocation, string serviceNumber, DateOnly dateOfPublish, int price, string? latitude = null, string? longitude = null)
            : base(id, serviceTypeId, userProfileId, title, description, serviceLocation, serviceNumber, dateOfPublish, price, latitude, longitude)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}