using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Imaar.Permissions;
using Imaar.ServiceTypes;

namespace Imaar.ServiceTypes
{
    public class ServiceTypesAppService : ServiceTypesAppServiceBase, IServiceTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceTypesAppService(IServiceTypeRepository serviceTypeRepository, ServiceTypeManager serviceTypeManager)
            : base(serviceTypeRepository, serviceTypeManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}