using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.UserEvalauations
{
    public class UserEvalauationManager : UserEvalauationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public UserEvalauationManager(IUserEvalauationRepository userEvalauationRepository)
            : base(userEvalauationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}