using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Imaar.MainAmenities
{
    public class MainAmenityManager : MainAmenityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MainAmenityManager(IMainAmenityRepository mainAmenityRepository)
            : base(mainAmenityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}